/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const IconData google = const IconData(0xe800, fontFamily: "CustomIcons");
  static const IconData ui_home = const IconData(0xec5e, fontFamily:"CustomIcons");
  static const IconData user_alt_3 = const IconData(0xecfd, fontFamily: "CustomIcons");
  static const IconData search_property = const IconData(0xed17, fontFamily: "CustomIcons");
  static const IconData search = const IconData(0xed1b, fontFamily: "CustomIcons");
  static const IconData sub_listing = const IconData(0xee03, fontFamily:"CustomIcons");
  static const IconData basket = const IconData(0xeeb0, fontFamily: "CustomIcons");
  static const IconData cart_alt = const IconData(0xeed1, fontFamily: "CustomIcons");
  static const IconData cart = const IconData(0xeed2, fontFamily: "CustomIcons");
  static const IconData menu = const IconData(0xf02f, fontFamily: "CustomIcons");
  static const IconData facebook = const IconData(0xf30c, fontFamily: "CustomIcons");
}
